<?php

global $b, $global_names;

$global_names = array(
		      'node_name_human' => 'Admin Note',
		      'node_name_machine' => 'admin_note',
		      'block_name_human' => 'Admin Block',
		      'block_name_machine' => 'admin_block',
		      'module_name_machine' => 'comment_node_block',
		      );

$b = 'sick and tired';

//==============================================================
/* Database Init/Schema */
//==============================================================

/* Creates the infinity_blah table when module is first installed */
function infinity_schema() {
  $schema['infinity_blah'] = array(
    'description' => 'A new table.', 
    'fields' => array(
      'id' => array(
        'description' => 'The primary identifier.', 
        'type' => 'serial', 
        'unsigned' => TRUE, 
        'not null' => TRUE,
      ), 
      'name' => array(
        'description' => 'The name.', 
        'type' => 'text', 
        'not null' => TRUE, 
      ), 
      'value' => array(
        'description' => 'The value.', 
        'type' => 'text', 
        'not null' => TRUE, 
      ), 
    ), 
    'unique keys' => array(
      'id' => array('id'),
    ), 
    'primary key' => array('id'),
  );
  return $schema;
}


//==============================================================
/* Node & Form Stuff */
//==============================================================

//Drupal adds this block type automatically
function comment_node_block_node_info() {
  global $global_names;
  $form = array();
  $form['admin_note'] = array(
			      /* 'type' => 'admin_note',  */
			      'name' => t($global_names['node_name_human']),
			      'module' =>'admin_note' ,
			      'description' => 'A note to be displayed in the admin_note_block',
			      'help' => 'Add a comment about any specific issue here',
			      'base' => 'node_content',
			      'has_title' => false,
			      /* 'title_label' => 'Add some super important note stuff here!', */
			      'has_body' => true,
			      'body_label' => 'Add some super important note stuff here!',
			      /* 'custom' => 1, */
			      /* 'modified' => 1, */
			      'min_word_count' => 0,
			      'locked' => 0,
			      'title_label' => 'Notes On Available Updates'
			      );
  return $form;
}

/* Form for adding a note to the admin_comment block
   Name should be of the form $globalname['node_name_machine']_form */
function admin_note_form($form_state) {
  $query = db_query("SELECT body FROM node_revisions WHERE nid = 9");
  $result = db_result($query);

  $form = array();
  $form['description'] = array(
			       '#type' => 'item',
			       /* '#prefix' => '<div><h2>',		 */
			       /* '#suffix' => '</h2></div>', */
			       '#title' => t('Important Notes Concerning The Following Updates'),
			       '#suffix' => '</br>',
			       );
  $form['name'] = array(
			/* '#prefix' => '<div><p>',		 */
			/* '#suffix' => '</p></div>', */
			'#title' => t('Your Name'),
			'#type' => 'textfield',
			'#size' => '20',
			/* '#default_value' => "Value", */
			/* '#description' => "Identify Yourself.", */
			'#required' => TRUE,
			'#suffix' => '</br>',
			);
  $form['body'] = array(
			/* '#prefix' => '<div><p>',		 */
			/* '#suffix' => '</p></div>', */
			'#title' => t('Add a note'),
			'#type' => 'textarea',
			'#cols' => '10',
			'#rows' => '2',
			/* '#default_value' => $result, */
			/* '#description' => "Tell Us About A Problem.", */
			'#required' => TRUE,
			'#suffix' => '</br>',
			);
  $form['submit'] = array(
			  '#type' => 'submit',
			  '#value' => 'Submit',
			  );
/* $form['junk'] = array( */
/* 			/\* '#prefix' => '<div><p>',		 *\/ */
/* 			/\* '#suffix' => '</p></div>', *\/ */
/* 			'#title' => t('Some Junke'), */
/* 			'#type' => 'textfield', */
/* 			'#size' => '20'); */
  return $form;
}

/* function admin_note_validate($form, &$form_state) { */
/* } */

function admin_note_form_submit($form, &$form_state) {
  /* db_query("INSERT INTO {table} (name, log, hidden) VALUES ('%s', %d, '%s')", $form_state['values']['name'], $form_state['values']['access']['log'],  $form_state['values']['hidden']); */
  /* drupal_set_message(t('Your form has been saved.')); */
  $query = db_query("SELECT body FROM node_revisions WHERE nid = 9");
  $result = db_result($query);
  /* echo "<h1>Behold!: " . $result . "</h1>"; */
  $new_note = $form_state['values']['body'];
  $new_note_taker = $form_state['values']['name'];
  $newest_text = $result . "\n" . "{$new_note}: <b>{$new_note_taker}</b>";
  $query = db_query("UPDATE node_revisions SET body='{$newest_text}', teaser='{$newest_text}' WHERE nid = 9");
}

//==============================================================
/* Block Helper Stuff */
//==============================================================

/* Create the view that we will see in the block
   - get the previous admin_note nodes 
   - display the form at the bottom of the block
*/
function get_admin_comment_view () {
  global $global_names;
  $temp = node_load(9);
  //node_show only seems to get the body of the node and not the title:
  $output = node_show($temp, NULL);  //second parameter is the first comment i believe
  /* $form =  drupal_get_form($global_names['node_name_machine'] . '_form'); */
  $form =  drupal_get_form('admin_note_form');
  return "</br><div>" . $output . "</div></br>" . $form;
  /* return $form; */
}

/* When someone submits the form in admin_comment block
   handle the data and save it to the database
   - probably should be part of the form validatation code for admin_note_form actually... 
*/
function save_admin_note_shit () {
}

//==============================================================
/* Block Init Stuff */
//==============================================================

//Drupal adds this block type automatically
function comment_node_block_block($op = 'list', $delta = 0, $edit = array()) {
  global $global_names;
  switch ($op) {
  case 'list':
    $blocks = array();
    $blocks[$global_names['block_name_machine']] = array(
							 'info' => t( $global_names['block_name_human']),
							 'region' => 'header',
							 'title' => t('Report/Configuration Notes'),
							 'weight' => -10,
							 'status' => 1,
							 'visibility' => 1,
							 /* 'properties' => array(), */ //Drupal7 only
							 'pages' => 'admin/reports/updates',
							 );
    return $blocks;
  case 'view':
    $block_content = array(
			   'subject' => "Insert Relevant Comments Regarding Modules",
			   /* 'content' => "Shazam", */
			   /* 'content' => drupal_get_form($global_names['node_name_machine'] . '_form'),  */
			   /* 'content' => node_add($global_names['node_name_machine']), */
			   'content' => get_admin_comment_view(),
			   );
    return $block_content;
    break;
    /* case 'save': */
    /* /\* case 'configure': *\/ */
    /* default: */
    /*   return admin_comment_get_block($delta); */
  }
}

//==============================================================
/* Helper functions */
//==============================================================

function get_all_nodes_of_type($node_type) {
  $result = db_query("SELECT nid FROM node WHERE type = '%s' ", $node_type);
  $nids = array();
  while ($obj = db_fetch_object ($result)) {
    $nids[] = $obj->nid;
  }
  return $nids;
}

function delete_all_nodes_of_type($node_type) {
  $nodes = get_all_nodes_of_type($node_type);
  foreach ($nodes as $node) {
    node_delete($node);
  }
}

function delete_blocks_from_module($block_module) {
  echo sprintf("DELETE FROM blocks WHERE module = '%s' ", $block_module);
  $result = db_query("DELETE FROM blocks WHERE module = '%s' ", $block_module);
}

//==============================================================
/* Module Lifecycle Functions */
//==============================================================

function comment_node_block_enable() {
  global $global_names;
  //Make sure that our admin_note block is created
  /* - this compares the blocks declared in moduls to the blocks in the table and reconciles? */
  _block_rehash();
}

function comment_node_block_disable() {
  global $global_names, $b;
  //Delete all nodes of node_type 'admin_note'
  //Delete 'admin_note' node type from the node_type table

  /* delete_all_nodes_of_type('admin_note'); */
  /* node_type_delete('admin_note'); */
  echo "The b is:   " . $b . "\n";
  echo "The size is:   " . count($global_names) . "\n";
  echo "Here it is: " . $global_names['module_name_machine'] . "\n";
  delete_blocks_from_module($global_names['module_name_machine']);
}

/* function comment_node_block_uninstall() { */
/*   //Delete all nodes of node_type 'admin_note' */
/*   //Delete 'admin_note' node type from the node_type table */
/* } */
  
//==============================================================
  
?>

